double len3(const double *x);
double len_squ3(const double *x);
double dot3(const double *res_pt x, const double *res_pt y);
double save_dot3(const double *res_pt x, const double *res_pt y);
void nvec3(const double *res_pt x, double *res_pt y);
void nvec3_ip(double *x, const double len);
void envec3_ip(double *x);
double dist3(const double *res_pt x, const double *res_pt y);
double dist_squ3(const double *res_pt x, const double *res_pt y);
void add3(const double *res_pt a, const double *res_pt b, double *c);
void sub3(const double *res_pt a, const double *res_pt b, double *c);
void mul3(const double *res_pt a, const double *res_pt b, double *c);
void linmul3(const double a, const double *res_pt b, double *c);
void linmul3_ip(const double a, double *b);
void addnmul3(const double *res_pt a, const double l, const double *res_pt b, double *c);
void lincomb3(const double la, const double *res_pt a, const double lb, const double *res_pt b, double *c);
void rev3(const double *res_pt x, double *res_pt y);
void rev3_ip(double *x);
void cross3(const double *a, const double *b, double *res_pt c);
void cross3_ip(const double *res_pt a, double *res_pt b);
void normedcross3(const double *res_pt a, const double *res_pt b, double *c);
void normedcross3_ip(const double *res_pt a, double *res_pt b);
double tripprod3(const double *a, const double *b, const double *c);
void inner_product3_mat_vec(const double *res_pt m, const double *res_pt v, double *res_pt out);
void inner_product3_mat_vec_ip(const double *res_pt m, double *res_pt v);
double cangl3(const double *res_pt a, const double *res_pt b);
double angl3(const double *res_pt a, const double *res_pt b);
void s_to_c3(const double *res_pt s, double *res_pt c);
void s_to_c3_ip(double *s);
void c_to_s3(const double *res_pt c, double *res_pt s);
void c_to_s3_ip(double *c);
double dist_poi_lin(const point3 *res_pt p, const line3 *res_pt l);
double dist_lin_lin_parallel(const line3 *res_pt l1, const line3 *res_pt l2);
double dist_lin_lin_skew(const line3 *res_pt l1, const line3 *res_pt l2);
double dist_poi_pla(const point3 *res_pt p, const plane3 *res_pt e);
double dist_lin_pla(const line3 *res_pt l, const plane3 *res_pt e);
double dist_pla_pla(const plane3 *res_pt e1, const plane3 *res_pt e2);
