void gen_mat_rot3_euler_xyz(double *m, const double *ea);
void gen_mat_rot3_euler_zx(double *m, const double *ea);
void gen_mat_rot3_euler_zpxpz(double *m, const double gamma, const double beta, const double alpha);
void gen_mat_rot3_n(double *res_pt m, const double *res_pt n, const double alpha);
void rot3_zx(double *p, const double axy, const double ayz);
void rottrans3_zx(double *p, const double axy, const double ayz, const double *t);
void rot3_xz(double *p, const double ayz, const double axy);
void rottrans3_xz(double *p, const double ayz, const double axy, const double *t);
void rot3_xpz(double *p, const double beta, const double alpha);
void rottrans3_xpz(double *p, const double beta, const double alpha, const double *t);
void rot3_z(double *p, const double axy);
void rottrans3_z(double *p, const double axy, const double *t);
void rot3_x(double *p, const double ayz);
void rottrans3_x(double *p, const double ayz, const double *t);
void rot3_y(double *p, const double azx);
void rottrans3_y(double *p, const double azx, const double *t);
void rot3_zpxpz(double *p, const double gamma, const double beta, const double alpha);
void rottrans3_zpxpz(double *p, const double gamma, const double beta, const double alpha, const double *t);
double angl3_xy(const double *p);
double angl3_yz(const double *p);
double angl3_xz(const double *p);
