void go_freeglut(int argc, char **argv);
uint init_main(int argc, char **argv);
void animate(void);
void visibility(const int vis);
void win_state(const int state);
void maindisplay(void);
void subdisplay(void);
void reshape(const int width, const int height);
void free_drawing_mem(void);
void close_all(void);
